# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8a85327efe1a8b3827f4aeef99df6b94669dec60470a8f5c88810881681cd5c772b4e1fcdfc4e500a9a1a08ce0f0f4d6a8c373bf82188800eaa341573852f0

test:
  secret_key_base: f3f1e996efa878878a32bbe1bee253d27f385497137ae1b53e5a6c7add988f096d37f42ec14e063b0046de8c13fccfffbedefd0b40a4cbfe472cca5204992a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
